# Generated by Django 5.0.6 on 2024-05-21 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tokenAuth', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tokenauth',
            old_name='UserStudent',
            new_name='user',
        ),
    ]
