# Generated by Django 5.0.2 on 2024-04-15 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userstudent',
            old_name='isMale',
            new_name='is_male',
        ),
    ]
