# Generated by Django 5.0.2 on 2024-04-15 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_rename_ismale_userstudent_is_male'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprof',
            old_name='isMale',
            new_name='is_male',
        ),
        migrations.RemoveField(
            model_name='userprof',
            name='review_number',
        ),
        migrations.RemoveField(
            model_name='userprof',
            name='review_score',
        ),
        migrations.AddField(
            model_name='reviewsprof',
            name='number_of_scores',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprof',
            name='email',
            field=models.EmailField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='userstudent',
            name='email',
            field=models.EmailField(max_length=64, unique=True),
        ),
    ]
