# Generated by Django 5.0.3 on 2024-04-11 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AvailabilityOfCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salle_name', models.CharField(max_length=32)),
                ('course_name', models.CharField(max_length=32)),
                ('taken_by_students', models.IntegerField()),
                ('capacity_of_students', models.IntegerField()),
                ('start_date', models.DateField()),
                ('number_of_hours', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Center',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('address', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=64)),
                ('phone', models.CharField(max_length=16)),
                ('capacity_of_students', models.IntegerField()),
            ],
        ),
    ]
